version: "3.3"

services:
  web:
     build: .
     container_name: web
     restart: always
     env_file:
       - .env
     expose:
       - "5000"

  front-end:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: front-end
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    links:
      - web
